# Generated by Django 4.1.7 on 2023-05-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='no',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
