# Generated by Django 4.1.7 on 2023-05-24 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order_day_order_no_alter_equipment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_proposal',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_proposal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user_details'),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='dt',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='filepath',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='remark',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='requirments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='tm',
            field=models.TimeField(),
        ),
    ]
