# Generated by Django 4.1.7 on 2023-05-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_user_proposal_user_id_user_proposal_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_proposal',
            name='user',
        ),
        migrations.AddField(
            model_name='user_proposal',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='dt',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='filepath',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='remark',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='requirments',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_proposal',
            name='tm',
            field=models.CharField(max_length=25),
        ),
    ]
