# Generated by Django 4.1.7 on 2023-05-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_user_proposal_user_user_proposal_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='age',
        ),
    ]
