# Generated by Django 4.1.7 on 2023-05-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_architect_details_descrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
