# Generated by Django 4.1.7 on 2023-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_order_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='user_proposal',
            name='status',
        ),
        migrations.AddField(
            model_name='user_proposal',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
